### ISSUE TITLE
Kein Login möglich

### ISSUE THREAD

**Issue by crusader85** [MiGoller/ioBroker.xplora#13]
Hi, 
leider kann ich mich nicht anmelden: Failed to login: 
{"response":{"errors":[{"code":"E000004","message":"Authentication failed."}],"data":{"issueToken":null},"status":200,"headers":{}},"request":{"query":"mutation IssueToken($countryPhoneNumber: String!, $phoneNumber: String!, $password: String!, $userLang: String!, $timeZone: String!)

Ist ein Adminaccount und das Passwort stimmt zu 100%

Viele Grüße

**Comment by MiGoller** [comment]
Guten Morgen. Geht mir auch grad so. Schaue ich mir an. Funktioniert der Login in der App? Bei mir funktioniert der Login in der App (wieder). Seit 2 Tagen gibt es zumindest für iOS eine neue Version `1.5.0` (vgl. https://apps.apple.com/de/app/xplora/id1521983878):

#### Neue Eigenschaften:

1. X6-Wiedergabe | Jetzt können Sie Benachrichtigungen über unbekannte Anrufe in den Uhreneinstellungen in der App aktivieren oder deaktivieren.

#### Verbesserungen und Fehlerbehebungen:

1. Neuer Look für die Uhreneinstellungen hinzugefügt.
2. Werksreset ohne eSIM-Option für X6 Play aus Sicherheitsgründen entfernt.
3. Behobener Bluetooth-Fehler nach eSIM-Download für einige der eSIM-Uhren.
4. Lokalisierungsverbesserungen für einige der Sprachen.

Nicht, dass sich da auch _API-Verbesserungen_ eingeschlichen haben. Neue Minor-Versionsnummern sollten zwar API-kompatibel sein, müssen es aber nicht.

**Comment by crusader85** [comment]
Der App-Login funktioniert einwandfrei. Da komme ich rein.

**Comment by MiGoller** [comment]
So, ich bin der Sache auf der Spur. Ich muss den Login für die API anpassen. Erste Tests sehen vielversprechend aus. Bitte nocj etwas Geduld.

**Comment by crusader85** [comment]
Danke, geht wieder

**Comment by Black-Hawk112** [comment]
Heute bei mir wieder kein Login möglich, App funktioniert. 
Bin ich alleine damit? ;-)
